Bye bye Truffle; Hello Saddle 🐎 (#511)
This patch adds Saddle, replacing Truffle as our Solidity framework. The [Saddle](https://github.com/compound-finance/saddle) framework lets us quickly run tests and coverage and improves the overall performance interacting with our contracts.

diff --git a/scenario/script/repl b/scenario/script/repl
--- a/scenario/script/repl
+++ b/scenario/script/repl
@@ -1,13 +1,13 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
-set -eo
+set -eo pipefail
 
 dir=`dirname $0`
-tsc_root="$(cd "$dir/.." && pwd)"
-proj_root="$(cd "$dir/../.." && pwd)"
-networks_root="$(cd "$dir/../../networks" && pwd)"
-test_root="$(cd "$dir/../../test" && pwd)"
-contracts_root="$(cd "$dir/../../contracts" && pwd)"
+tsc_root="$dir/.."
+proj_root="$dir/../.."
+networks_root="$dir/../../networks"
+test_root="$dir/../../test"
+contracts_root="$dir/../../contracts"
 network=${NETWORK:-development}
 script="$SCRIPT"
 verbose="$VERBOSE"
@@ -23,9 +23,6 @@ while getopts ":hdn:e:s:vt" arg; do
 		d) # Dry run
 			dry_run="true"
 			;;
-		h) # Hypothetical
-			hypothetical="true"
-			;;
 		e) # Add variables for script (key=value,key2=value2)
 			env_vars="$OPTARG"
 			;;
@@ -33,17 +30,10 @@ while getopts ":hdn:e:s:vt" arg; do
 			network=$OPTARG
 			;;
 		s) # Specify a script to run
-			if [[ "$OSTYPE" == "darwin"* ]]; then
-				# Darwin doesn't support readlink -f to get absolute path...
-				script_file=$OPTARG
-			else
-				script_file="$(readlink -f "$OPTARG")"
-			fi
-
-			[ ! -f "$script_file" ] \
-				&& echo "Cannot find script $script_file" \
+			script=$OPTARG
+			[ ! -f "$script" ] \
+				&& echo "Cannot find script $script" \
 				&& exit 1
-			script+=("$OPTARG")
 			;;
 		t) # Don't build TSC
 			no_tsc="true"
@@ -54,33 +44,13 @@ while getopts ":hdn:e:s:vt" arg; do
 			;;
 
 		h | *) # Display help.
-			usa te
+			usage
 			exit 0
 			;;
 	esac
 done
 
-script=$(printf ",%s" "${script[@]}")
-script=${script:2}
+[[ -z $no_tsc ]] && "$dir/tsc"
+[[ -z $no_compile ]] && "$proj_root/script/compile"
 
-if [ ! $network = "mainnet" ]; then
-	function cleanup {
-		mv "$contracts_root/test" "$test_root/contracts"
-	}
-
-	trap cleanup EXIT
-
-	mv "$test_root/contracts" "$contracts_root/test"
-
-	# Compile with test contracts
-	[[ -z $no_compile ]] && solc --combined-json bin,abi --optimize contracts/*.sol contracts/**/*.sol --allow-paths ./contracts,./contracts/test > networks/${network}-contracts.json
-else
-	# Compile without test contracts
-	[[ -z $no_compile ]] && solc --combined-json bin,abi --optimize contracts/*.sol > networks/${network}-contracts.json
-fi
-
-[[ ! -d ./.tsbuilt || -z $no_tsc ]] && . "$dir/tsc"
-
-[[ -z $no_compile ]] && node --stack_size=10000 "$proj_root/node_modules/truffle/build/cli.bundled.js" compile
-
-proj_root="$proj_root" env_vars="$env_vars" dry_run="$dry_run" hypothetical="$hypothetical" script="$script" network="$network" verbose="$verbose" npx truffle exec --network "$network" "$tsc_root/.tsbuilt/Repl.js"
+proj_root="$proj_root" env_vars="$env_vars" dry_run="$dry_run" script="$script" network="$network" verbose="$verbose" node "$tsc_root/.tsbuilt/repl.js"
